# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/cgsn-parsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - parsers-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - parsers-dependencies-

      - run:
          name: install dependencies
          command: |
            conda update -n base conda
            conda config --add channels conda-forge
            conda install --yes circleci-helpers
            conda env create --yes --file requirements.txt -n cgsn-parsers

      - save_cache:
          key: parsers-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            source activate cgsn-parsers
            python -m unittest discover

      - store_artifacts:
          path: test-reports
          destination: test-reports
